/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenderIndexRouteImport } from './routes/tender.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as FreelanceIndexRouteImport } from './routes/freelance.index'
import { Route as ServicesWorkflowRouteImport } from './routes/services.workflow'
import { Route as ServicesRegisterRouteImport } from './routes/services.register'
import { Route as ServicesOrdersRouteImport } from './routes/services.orders'
import { Route as ServicesBookingsRouteImport } from './routes/services.bookings'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding.company'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as FreelanceProfileRouteImport } from './routes/freelance.profile'
import { Route as FreelanceOrdersRouteImport } from './routes/freelance.orders'
import { Route as FreelanceNewRouteImport } from './routes/freelance.new'
import { Route as FreelanceDashboardRouteImport } from './routes/freelance.dashboard'
import { Route as FreelanceGigIdRouteImport } from './routes/freelance.$gigId'
import { Route as CompanyUsersRouteImport } from './routes/company.users'
import { Route as CompanyApplicantsRouteImport } from './routes/company.applicants'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSkillWorkersRouteImport } from './routes/admin.skill-workers'
import { Route as AdminServiceDisputesRouteImport } from './routes/admin.service-disputes'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminPostJobRouteImport } from './routes/admin.post-job'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCvParsingRouteImport } from './routes/admin.cv-parsing'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminCompaniesCompanyIdRouteImport } from './routes/admin.companies.$companyId'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderIndexRoute = TenderIndexRouteImport.update({
  id: '/tender/',
  path: '/tender/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceIndexRoute = FreelanceIndexRouteImport.update({
  id: '/freelance/',
  path: '/freelance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWorkflowRoute = ServicesWorkflowRouteImport.update({
  id: '/services/workflow',
  path: '/services/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRegisterRoute = ServicesRegisterRouteImport.update({
  id: '/services/register',
  path: '/services/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOrdersRoute = ServicesOrdersRouteImport.update({
  id: '/services/orders',
  path: '/services/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBookingsRoute = ServicesBookingsRouteImport.update({
  id: '/services/bookings',
  path: '/services/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/onboarding/company',
  path: '/onboarding/company',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceProfileRoute = FreelanceProfileRouteImport.update({
  id: '/freelance/profile',
  path: '/freelance/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceOrdersRoute = FreelanceOrdersRouteImport.update({
  id: '/freelance/orders',
  path: '/freelance/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceNewRoute = FreelanceNewRouteImport.update({
  id: '/freelance/new',
  path: '/freelance/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceDashboardRoute = FreelanceDashboardRouteImport.update({
  id: '/freelance/dashboard',
  path: '/freelance/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceGigIdRoute = FreelanceGigIdRouteImport.update({
  id: '/freelance/$gigId',
  path: '/freelance/$gigId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyUsersRoute = CompanyUsersRouteImport.update({
  id: '/company/users',
  path: '/company/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyApplicantsRoute = CompanyApplicantsRouteImport.update({
  id: '/company/applicants',
  path: '/company/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSkillWorkersRoute = AdminSkillWorkersRouteImport.update({
  id: '/admin/skill-workers',
  path: '/admin/skill-workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceDisputesRoute = AdminServiceDisputesRouteImport.update({
  id: '/admin/service-disputes',
  path: '/admin/service-disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostJobRoute = AdminPostJobRouteImport.update({
  id: '/admin/post-job',
  path: '/admin/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCvParsingRoute = AdminCvParsingRouteImport.update({
  id: '/admin/cv-parsing',
  path: '/admin/cv-parsing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesCompanyIdRoute = AdminCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AdminCompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/matches': typeof MatchesRoute
  '/plans': typeof PlansRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/settings': typeof SettingsRoute
  '/trust': typeof TrustRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/cv-parsing': typeof AdminCvParsingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/post-job': typeof AdminPostJobRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/service-disputes': typeof AdminServiceDisputesRoute
  '/admin/skill-workers': typeof AdminSkillWorkersRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/users': typeof CompanyUsersRoute
  '/freelance/$gigId': typeof FreelanceGigIdRoute
  '/freelance/dashboard': typeof FreelanceDashboardRoute
  '/freelance/new': typeof FreelanceNewRoute
  '/freelance/orders': typeof FreelanceOrdersRoute
  '/freelance/profile': typeof FreelanceProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/services/bookings': typeof ServicesBookingsRoute
  '/services/orders': typeof ServicesOrdersRoute
  '/services/register': typeof ServicesRegisterRoute
  '/services/workflow': typeof ServicesWorkflowRoute
  '/freelance/': typeof FreelanceIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tender/': typeof TenderIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/matches': typeof MatchesRoute
  '/plans': typeof PlansRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/settings': typeof SettingsRoute
  '/trust': typeof TrustRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/cv-parsing': typeof AdminCvParsingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/post-job': typeof AdminPostJobRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/service-disputes': typeof AdminServiceDisputesRoute
  '/admin/skill-workers': typeof AdminSkillWorkersRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/users': typeof CompanyUsersRoute
  '/freelance/$gigId': typeof FreelanceGigIdRoute
  '/freelance/dashboard': typeof FreelanceDashboardRoute
  '/freelance/new': typeof FreelanceNewRoute
  '/freelance/orders': typeof FreelanceOrdersRoute
  '/freelance/profile': typeof FreelanceProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/services/bookings': typeof ServicesBookingsRoute
  '/services/orders': typeof ServicesOrdersRoute
  '/services/register': typeof ServicesRegisterRoute
  '/services/workflow': typeof ServicesWorkflowRoute
  '/freelance': typeof FreelanceIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tender': typeof TenderIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/matches': typeof MatchesRoute
  '/plans': typeof PlansRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/resume': typeof ResumeRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/settings': typeof SettingsRoute
  '/trust': typeof TrustRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/cv-parsing': typeof AdminCvParsingRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/post-job': typeof AdminPostJobRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/service-disputes': typeof AdminServiceDisputesRoute
  '/admin/skill-workers': typeof AdminSkillWorkersRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/users': typeof CompanyUsersRoute
  '/freelance/$gigId': typeof FreelanceGigIdRoute
  '/freelance/dashboard': typeof FreelanceDashboardRoute
  '/freelance/new': typeof FreelanceNewRoute
  '/freelance/orders': typeof FreelanceOrdersRoute
  '/freelance/profile': typeof FreelanceProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/services/bookings': typeof ServicesBookingsRoute
  '/services/orders': typeof ServicesOrdersRoute
  '/services/register': typeof ServicesRegisterRoute
  '/services/workflow': typeof ServicesWorkflowRoute
  '/freelance/': typeof FreelanceIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tender/': typeof TenderIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/auth'
    | '/billing'
    | '/matches'
    | '/plans'
    | '/post-job'
    | '/profile'
    | '/resume'
    | '/saved-jobs'
    | '/settings'
    | '/trust'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/branding'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/cv-parsing'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/plans'
    | '/admin/post-job'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/service-disputes'
    | '/admin/skill-workers'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/users'
    | '/companies/$companyId'
    | '/company/applicants'
    | '/company/users'
    | '/freelance/$gigId'
    | '/freelance/dashboard'
    | '/freelance/new'
    | '/freelance/orders'
    | '/freelance/profile'
    | '/jobs/$jobId'
    | '/onboarding/company'
    | '/services/bookings'
    | '/services/orders'
    | '/services/register'
    | '/services/workflow'
    | '/freelance/'
    | '/jobs/'
    | '/services/'
    | '/tender/'
    | '/admin/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/auth'
    | '/billing'
    | '/matches'
    | '/plans'
    | '/post-job'
    | '/profile'
    | '/resume'
    | '/saved-jobs'
    | '/settings'
    | '/trust'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/branding'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/cv-parsing'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/plans'
    | '/admin/post-job'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/service-disputes'
    | '/admin/skill-workers'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/users'
    | '/companies/$companyId'
    | '/company/applicants'
    | '/company/users'
    | '/freelance/$gigId'
    | '/freelance/dashboard'
    | '/freelance/new'
    | '/freelance/orders'
    | '/freelance/profile'
    | '/jobs/$jobId'
    | '/onboarding/company'
    | '/services/bookings'
    | '/services/orders'
    | '/services/register'
    | '/services/workflow'
    | '/freelance'
    | '/jobs'
    | '/services'
    | '/tender'
    | '/admin/companies/$companyId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/auth'
    | '/billing'
    | '/matches'
    | '/plans'
    | '/post-job'
    | '/profile'
    | '/resume'
    | '/saved-jobs'
    | '/settings'
    | '/trust'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/branding'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/cv-parsing'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/plans'
    | '/admin/post-job'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/service-disputes'
    | '/admin/skill-workers'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/users'
    | '/companies/$companyId'
    | '/company/applicants'
    | '/company/users'
    | '/freelance/$gigId'
    | '/freelance/dashboard'
    | '/freelance/new'
    | '/freelance/orders'
    | '/freelance/profile'
    | '/jobs/$jobId'
    | '/onboarding/company'
    | '/services/bookings'
    | '/services/orders'
    | '/services/register'
    | '/services/workflow'
    | '/freelance/'
    | '/jobs/'
    | '/services/'
    | '/tender/'
    | '/admin/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  MatchesRoute: typeof MatchesRoute
  PlansRoute: typeof PlansRoute
  PostJobRoute: typeof PostJobRoute
  ProfileRoute: typeof ProfileRoute
  ResumeRoute: typeof ResumeRoute
  SavedJobsRoute: typeof SavedJobsRoute
  SettingsRoute: typeof SettingsRoute
  TrustRoute: typeof TrustRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCompaniesRoute: typeof AdminCompaniesRouteWithChildren
  AdminCvParsingRoute: typeof AdminCvParsingRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminPostJobRoute: typeof AdminPostJobRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminServiceDisputesRoute: typeof AdminServiceDisputesRoute
  AdminSkillWorkersRoute: typeof AdminSkillWorkersRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompanyApplicantsRoute: typeof CompanyApplicantsRoute
  CompanyUsersRoute: typeof CompanyUsersRoute
  FreelanceGigIdRoute: typeof FreelanceGigIdRoute
  FreelanceDashboardRoute: typeof FreelanceDashboardRoute
  FreelanceNewRoute: typeof FreelanceNewRoute
  FreelanceOrdersRoute: typeof FreelanceOrdersRoute
  FreelanceProfileRoute: typeof FreelanceProfileRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  ServicesBookingsRoute: typeof ServicesBookingsRoute
  ServicesOrdersRoute: typeof ServicesOrdersRoute
  ServicesRegisterRoute: typeof ServicesRegisterRoute
  ServicesWorkflowRoute: typeof ServicesWorkflowRoute
  FreelanceIndexRoute: typeof FreelanceIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TenderIndexRoute: typeof TenderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender/': {
      id: '/tender/'
      path: '/tender'
      fullPath: '/tender/'
      preLoaderRoute: typeof TenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/': {
      id: '/freelance/'
      path: '/freelance'
      fullPath: '/freelance/'
      preLoaderRoute: typeof FreelanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/workflow': {
      id: '/services/workflow'
      path: '/services/workflow'
      fullPath: '/services/workflow'
      preLoaderRoute: typeof ServicesWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/register': {
      id: '/services/register'
      path: '/services/register'
      fullPath: '/services/register'
      preLoaderRoute: typeof ServicesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/orders': {
      id: '/services/orders'
      path: '/services/orders'
      fullPath: '/services/orders'
      preLoaderRoute: typeof ServicesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bookings': {
      id: '/services/bookings'
      path: '/services/bookings'
      fullPath: '/services/bookings'
      preLoaderRoute: typeof ServicesBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/profile': {
      id: '/freelance/profile'
      path: '/freelance/profile'
      fullPath: '/freelance/profile'
      preLoaderRoute: typeof FreelanceProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/orders': {
      id: '/freelance/orders'
      path: '/freelance/orders'
      fullPath: '/freelance/orders'
      preLoaderRoute: typeof FreelanceOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/new': {
      id: '/freelance/new'
      path: '/freelance/new'
      fullPath: '/freelance/new'
      preLoaderRoute: typeof FreelanceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/dashboard': {
      id: '/freelance/dashboard'
      path: '/freelance/dashboard'
      fullPath: '/freelance/dashboard'
      preLoaderRoute: typeof FreelanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/$gigId': {
      id: '/freelance/$gigId'
      path: '/freelance/$gigId'
      fullPath: '/freelance/$gigId'
      preLoaderRoute: typeof FreelanceGigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/users': {
      id: '/company/users'
      path: '/company/users'
      fullPath: '/company/users'
      preLoaderRoute: typeof CompanyUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/applicants': {
      id: '/company/applicants'
      path: '/company/applicants'
      fullPath: '/company/applicants'
      preLoaderRoute: typeof CompanyApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/skill-workers': {
      id: '/admin/skill-workers'
      path: '/admin/skill-workers'
      fullPath: '/admin/skill-workers'
      preLoaderRoute: typeof AdminSkillWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-disputes': {
      id: '/admin/service-disputes'
      path: '/admin/service-disputes'
      fullPath: '/admin/service-disputes'
      preLoaderRoute: typeof AdminServiceDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/post-job': {
      id: '/admin/post-job'
      path: '/admin/post-job'
      fullPath: '/admin/post-job'
      preLoaderRoute: typeof AdminPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cv-parsing': {
      id: '/admin/cv-parsing'
      path: '/admin/cv-parsing'
      fullPath: '/admin/cv-parsing'
      preLoaderRoute: typeof AdminCvParsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies/$companyId': {
      id: '/admin/companies/$companyId'
      path: '/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AdminCompaniesCompanyIdRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
  }
}

interface AdminCompaniesRouteChildren {
  AdminCompaniesCompanyIdRoute: typeof AdminCompaniesCompanyIdRoute
}

const AdminCompaniesRouteChildren: AdminCompaniesRouteChildren = {
  AdminCompaniesCompanyIdRoute: AdminCompaniesCompanyIdRoute,
}

const AdminCompaniesRouteWithChildren = AdminCompaniesRoute._addFileChildren(
  AdminCompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  MatchesRoute: MatchesRoute,
  PlansRoute: PlansRoute,
  PostJobRoute: PostJobRoute,
  ProfileRoute: ProfileRoute,
  ResumeRoute: ResumeRoute,
  SavedJobsRoute: SavedJobsRoute,
  SettingsRoute: SettingsRoute,
  TrustRoute: TrustRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCompaniesRoute: AdminCompaniesRouteWithChildren,
  AdminCvParsingRoute: AdminCvParsingRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminPostJobRoute: AdminPostJobRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminServiceDisputesRoute: AdminServiceDisputesRoute,
  AdminSkillWorkersRoute: AdminSkillWorkersRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompanyApplicantsRoute: CompanyApplicantsRoute,
  CompanyUsersRoute: CompanyUsersRoute,
  FreelanceGigIdRoute: FreelanceGigIdRoute,
  FreelanceDashboardRoute: FreelanceDashboardRoute,
  FreelanceNewRoute: FreelanceNewRoute,
  FreelanceOrdersRoute: FreelanceOrdersRoute,
  FreelanceProfileRoute: FreelanceProfileRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  OnboardingCompanyRoute: OnboardingCompanyRoute,
  ServicesBookingsRoute: ServicesBookingsRoute,
  ServicesOrdersRoute: ServicesOrdersRoute,
  ServicesRegisterRoute: ServicesRegisterRoute,
  ServicesWorkflowRoute: ServicesWorkflowRoute,
  FreelanceIndexRoute: FreelanceIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TenderIndexRoute: TenderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
