/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenderIndexRouteImport } from './routes/tender.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding.company'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as CompanyUsersRouteImport } from './routes/company.users'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminPostJobRouteImport } from './routes/admin.post-job'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminCompaniesCompanyIdRouteImport } from './routes/admin.companies.$companyId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderIndexRoute = TenderIndexRouteImport.update({
  id: '/tender/',
  path: '/tender/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/onboarding/company',
  path: '/onboarding/company',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyUsersRoute = CompanyUsersRouteImport.update({
  id: '/company/users',
  path: '/company/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostJobRoute = AdminPostJobRouteImport.update({
  id: '/admin/post-job',
  path: '/admin/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesCompanyIdRoute = AdminCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AdminCompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/plans': typeof PlansRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/post-job': typeof AdminPostJobRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/users': typeof CompanyUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/jobs/': typeof JobsIndexRoute
  '/tender/': typeof TenderIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/plans': typeof PlansRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/post-job': typeof AdminPostJobRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/users': typeof CompanyUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/jobs': typeof JobsIndexRoute
  '/tender': typeof TenderIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/plans': typeof PlansRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/companies': typeof AdminCompaniesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/post-job': typeof AdminPostJobRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/users': typeof CompanyUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/jobs/': typeof JobsIndexRoute
  '/tender/': typeof TenderIndexRoute
  '/admin/companies/$companyId': typeof AdminCompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/auth'
    | '/billing'
    | '/plans'
    | '/post-job'
    | '/profile'
    | '/settings'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/branding'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/plans'
    | '/admin/post-job'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/users'
    | '/company/users'
    | '/jobs/$jobId'
    | '/onboarding/company'
    | '/jobs/'
    | '/tender/'
    | '/admin/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/auth'
    | '/billing'
    | '/plans'
    | '/post-job'
    | '/profile'
    | '/settings'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/branding'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/plans'
    | '/admin/post-job'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/users'
    | '/company/users'
    | '/jobs/$jobId'
    | '/onboarding/company'
    | '/jobs'
    | '/tender'
    | '/admin/companies/$companyId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/auth'
    | '/billing'
    | '/plans'
    | '/post-job'
    | '/profile'
    | '/settings'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/branding'
    | '/admin/candidates'
    | '/admin/categories'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/plans'
    | '/admin/post-job'
    | '/admin/review'
    | '/admin/roles'
    | '/admin/users'
    | '/company/users'
    | '/jobs/$jobId'
    | '/onboarding/company'
    | '/jobs/'
    | '/tender/'
    | '/admin/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  PlansRoute: typeof PlansRoute
  PostJobRoute: typeof PostJobRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCompaniesRoute: typeof AdminCompaniesRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminPostJobRoute: typeof AdminPostJobRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CompanyUsersRoute: typeof CompanyUsersRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  JobsIndexRoute: typeof JobsIndexRoute
  TenderIndexRoute: typeof TenderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender/': {
      id: '/tender/'
      path: '/tender'
      fullPath: '/tender/'
      preLoaderRoute: typeof TenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/users': {
      id: '/company/users'
      path: '/company/users'
      fullPath: '/company/users'
      preLoaderRoute: typeof CompanyUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/post-job': {
      id: '/admin/post-job'
      path: '/admin/post-job'
      fullPath: '/admin/post-job'
      preLoaderRoute: typeof AdminPostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies/$companyId': {
      id: '/admin/companies/$companyId'
      path: '/$companyId'
      fullPath: '/admin/companies/$companyId'
      preLoaderRoute: typeof AdminCompaniesCompanyIdRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
  }
}

interface AdminCompaniesRouteChildren {
  AdminCompaniesCompanyIdRoute: typeof AdminCompaniesCompanyIdRoute
}

const AdminCompaniesRouteChildren: AdminCompaniesRouteChildren = {
  AdminCompaniesCompanyIdRoute: AdminCompaniesCompanyIdRoute,
}

const AdminCompaniesRouteWithChildren = AdminCompaniesRoute._addFileChildren(
  AdminCompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  PlansRoute: PlansRoute,
  PostJobRoute: PostJobRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCompaniesRoute: AdminCompaniesRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminPostJobRoute: AdminPostJobRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  CompanyUsersRoute: CompanyUsersRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  OnboardingCompanyRoute: OnboardingCompanyRoute,
  JobsIndexRoute: JobsIndexRoute,
  TenderIndexRoute: TenderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
